{{- if .Values.schema.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.component }}
  namespace: argocd
  labels:
    appName: {{ .Values.labels.appName }}
    projectName: {{ .Chart.Name }}
spec:
  template:
    metadata:
      labels:
        appName: {{ .Values.labels.appName }}
        projectName: {{ .Chart.Name }}
    spec:
      volumes:
        - name: secrets
          emptyDir: {}
      initContainers:
        - name: get-secrets
          image: 041445559784.dkr.ecr.us-east-1.amazonaws.com/vault-initcontainer:1.0.1
          env:
            - name: VAULT_ADDR
              value: "https://vault-internal.pdevops78.online:8200"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token
                  key: token
            - name: SECRET_NAME
              value: roboshop-dev/catalogue
            - name: VAULT_SKIP_VERIFY
              value: "TRUE"
          volumeMounts:
            - name: secrets
              mountPath: /data

      containers:
        - name: schema
          image: 041445559784.dkr.ecr.us-east-1.amazonaws.com/backend-schema:{{ .Values.schema.schema_imageVersion }}
          env:
            - name: db_type
              value: "{{ .Values.schema.db_type }}"
          volumeMounts:
            - name: secrets
              mountPath: /data
      restartPolicy: Never
  backoffLimit: 1
  {{- end }}
