metadata:
  name: catalogue
component: catalogue

initContainers:
  enabled: true
  vault_init_containers.enabled: true
  schema_init_containers.enabled: false

schema:
  enabled: false

containers:
  appVersion: 2.0.3

service:
  type: ClusterIP
ports:
  protocol: TCP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false
