metadata:
  name: catalogue
component: catalogue

initContainers:
  enabled: true
  intContainers.enabled: true
schema:
  enabled: false
  schemaContainers.enabled: true

containers:
  appVersion: 2.0.3

service:
  type: ClusterIP
ports:
  protocol: TCP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false
